### PR TITLE
added raw html support in messages

### PR DESCRIPTION
**Pull request by glutaminefree**

### CODE REVIEW

**Comment by dgknca** [comment]
Hi! Thanks for PR! I thought it would be okay to use `innerHTML` instead of `textContent` and merged this pull request https://github.com/dgknca/simple-notify/pull/5.

**Comment by dgknca** [comment]
and published 0.5.0

**Comment by glutaminefree** [comment]
image
Something wrong with build - there are no dist files.

**Comment by dgknca** [comment]
oh sorry I had deleted dist files and forgot publishing them. published in v0.5.1

**Comment by glutaminefree** [comment]
And now 0.5.1 have no changes for HTML support :(
image

**Comment by glutaminefree** [comment]
Sorry for that small chaos, man :)

**Comment by glutaminefree** [comment]
And you need to update GitHub Pages docs after ;)

**Comment by dgknca** [comment]
Look at this pen https://codepen.io/dgknca/pen/rNyWKYG

No update needed for docs, I just changed this line :) [`e71eebb#187`](https://github.com/dgknca/simple-notify/commit/e71eebb7911ae36229244d9c2b715a42bbd3e983#diff-fbc70145ad475990ac05347a804a734e94748579176e9aa4208d3ea7d90f015aL187)

**Comment by dgknca** [comment]
haha sorry, demo version updated

**Comment by glutaminefree** [comment]
image
it looks like some styles are broken

**Comment by dgknca** [comment]
my bad 🤦‍♂️ Updated it again again again

**Comment by glutaminefree** [comment]
Now all works great! Thanks!

**Pull request closed without merging**
