### PR TITLE
Minor fixes and packages update

### PR DESCRIPTION
**Pull request by giuliolastra**
Hi,
thanks for your simple notify, is so easy to use and lightweight! I did some minor updates to the packages, moreover I added `node-sass` because `yarn watch` was failing due to missing package `node-sass`. 
I also made a small fix in the demo script, in particular on custom icons and custom classes, because there were too many quotes.

Let me know if you like it.

Thanks!
Giulio

### CODE REVIEW

**Comment by giuliolastra** [comment]
For me is ok.
However with those quotes the generator into the demo will reproduce icons (standard chars/unicodechars/emoji/html tags with `'` before and after the string, so all will be reproduced with quotes around. Here's an example:

image

Same happens looking on Chrome inspector with customClass.

**Comment by dgknca** [comment]
@giuliolastra Thanks a lot. I hadn't noticed that. Fixed it https://github.com/dgknca/simple-notify/commit/6994aa7561a2f7db93c72daff7202d10385f08e8

**Comment by giuliolastra** [comment]
Great! 👍🏼 when you can please tag it and release it (also on npm). Thanks a lot!

**Comment by dgknca** [comment]
Released v0.5.4

**Pull request merged**
